export class TermsAndCondition{
inv_termsandCondition_master_id:number;  
termsAndCondition:string;
inv_termsandCondition_master_deleted_by_id:number;
inv_termsandCondition_master_deleted_by_name:string;
termsandConditionMasterDeleteFlag:number;
inv_termsandCondition_master_deleted_date:Date;
inv_termsandCondition_master_create_date:Date;
inv_termsandCondition_master_update_date:Date;
inv_name:string;
temsAndCondStatus:string;
}